name: Auto Update M3U

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run script (DEBUG)
        run: |
          echo "Running script..."
          ls -la
          python main.py

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add hoadaopro.m3u

          git diff --cached --quiet || git commit -m "auto update m3u"

          git push
